USE euro;

-- Add billing information columns to orders table
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS first_name VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS last_name VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS email VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS final_amount DECIMAL(10, 2) NULL;
